apiVersion:  ec2.aws.m.upbound.io/v1beta1
kind: Instance
metadata:
  name: customer-a-test1
  namespace: customer-a
spec:
  forProvider:
    region: ap-south-1
    instanceType: t2.micro
    ami: ami-066c4849e6b3a1e3d
    tags:
      Name: customer-a-test1
      Customer: customer-a
  providerConfigRef:
    name: customer-a
