apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: customer-a-test2
  namespace: customer-a
spec:
  forProvider:
    region: ap-south-1
    instanceType: t2.micro
    ami: ami-066c4849e6b3a1e3d
    state: stopped
    tags:
      Name: customer-a-test2
      Customer: customer-a
  providerConfigRef:
    name: customer-a
    kind: ProviderConfig
